# Set the language
language: node_js

# Set the node version
node_js:
    - "12"

# env:
#     - git=checkout scm

services:
    # Use docker command line and mongodb
    - docker
    - mongodb

jobs:
    include:
        - stage: clean
          script: 
          - git clean -dfxq
          - git stash
        - stage: setup
          script: npm install
        - stage: lint
          script: npm run lint
        - stage: unit test
          script: npm run test:unit
        # - stage: build
        #     script:
        #     - ./scripts/docker_build.sh ${git.GIT_COMMIT}"
        #     - ./scripts/docker_push.sh ${git.GIT_COMMIT}"

# before_install:
#     - docker build -t stafsetning-api .

# script:
#     # Run tests
#     - npm run test

# # deploy:
# #     # Build Docker container and push to Docker Hub
# #     provider: script
# #     script: bash scripts/deploy.sh
# #     on:
# #         branch: master

# after_script:
#     - docker-compose up
