# Set the language
language: node_js

# Set the node version
node_js:
    - "12"

services:
    # Use docker command line and mongodb
    - docker
    # - mongodb

jobs:
    include:
        - stage: clean, setup, lint, unit test and build
          script: 
          - git clean -dfxq
          - git stash
          - npm install
          - npm run lint
          - npm run test:unit
          - sh ./scripts/docker_build.sh $TRAVIS_COMMIT

# before_install:
#     - docker build -t stafsetning-api .

# script:
#     # Run tests
#     - npm run test

# # deploy:
# #     # Build Docker container and push to Docker Hub
# #     provider: script
# #     script: bash scripts/deploy.sh
# #     on:
# #         branch: master

# after_script:
#     - docker-compose up
