language: node_js
node_js:
- '12'
services:
- docker
env:
  global:
  - IMAGE_NAME=gabriels17/stafsetning-api
  - REGISTRY_USER=gabriels17
  - secure: eDpLwB8lFgrfNqjAZTRwqsARF9MS1m687tzf0f8lkQzNtSsqx8uR98ZkmsLET5/sdI1fIBqV2IuJ3hycYGYcVhFqkhkeNEYLi4brQY9dLBaUQTduesgGzcBW8bkojac/cO3+N6ACD/yW70uxVJcPwxAPTOeHQiOCNyrnjjuwI86uHaHJY1uR5fADkhemwUgOrK1APBP+0xc4ssNuMnbK7gYvWpCbOaEDze3mVPKvA6SocEip8ZFu+NVL2KU8fe1b56A37hXlXVgH9CF7TfYdczGNw1LkXwoTdnb5LSLyXsvMourei8Ya89GEXz2CyqE9SswLknj8z0AAqk27KEjdRm5EZxwLrIQvjsqZu8OZbEdEElYPepzDCi3Zy9pHWHNGnfvc5tkXOXaqnl+LWfk8yQUiwN4HpIsRBbyBxTP/XhtkddXM6NLfTmBE9Xao1m+fRYGsWrAYxK3RABy11r0LyHyi8PLuIhxPuKfs/0jQ508a8kQR14w8YhFe4wOLK/E1zlIxCzj+364yboFZQpk5L5qU9wVtdsRzL52kKIicx6pu+dkPmo4JY2SkwAQV8eEdT8wAJujML6geFAsKftT+hmAoSYxRoXTOWiDSPV7/plv5TZ8xUNkOgSDKZGKbmEUBd2xL6FLimWw7TfHOocssajpO+KTdt2h3caNxhOMCukY=
jobs:
  include:
  - stage: clean, setup, lint, unit test
    script:
    - git clean -dfxq
    - git stash
    - npm install
    - npm run lint
    - npm run test:unit
  - stage: build
    script:
    - "./scripts/docker_deploy.sh $IMAGE_NAME $REGISTRY_USER $REGISTRY_PASS $TRAVIS_COMMIT"
